library(RGCCTranslationUnit)

autoGenerateDir = "."
tu = parseTU(paste(autoGenerateDir, "wx.cpp.tu", sep = .Platform$file.sep))

wxClasses = getClassNodes(tu, "button")

ms = getClassMethods(tu [[ wxClasses[["wxButton"]] ]])
cc = resolveType(ms[[2]], tu)
createMethodBinding(cc, "wxButton")

