library(RGCCTranslationUnit)

autoGenerateDir = "."
tu = parseTU(paste(autoGenerateDir, "wx.cpp.tu", sep = .Platform$file.sep))

wxClasses = getClassNodes(tu, "htmlpars")


ms = getClassMethods(tu [[ wxClasses[["wxHtmlTagHandler"]] ]])
resolved = lapply(ms, resolveType, tu)
o = createDerivedClass("RwxHtmlTagHandler", list(wxHtmlTagHandler = resolved), "wxHtmlTagHandler")


o = createDerivedClass("RwxApp", resolved, classes) # check.
 
