EVT_SPIN_UP = wxEVT_SCROLL_LINEUP
EVT_SPIN_DOWN = wxEVT_SCROLL_LINEDOWN
EVT_SPIN = wxEVT_SCROLL_THUMBTACK
EVT_SPINCTRL = wxEVT_COMMAND_SPINCTRL_UPDATED


# Iso mappings, i.e those that have a simple wx prefix
isoEventMapping = 
c("TASKBAR",  # 
  "GRID",   # no _CMD_ versions which take a second argument.
  
  

EVT_WINDOW_CREATE = wxEVT_CREATE
EVT_WINDOW_DESTROY = wxEVT_DELETE
EVT_PAINT = wxEVT_PAINT
EVT_ERASE_BACKGROUND = wxEVT_ERASE_BACKGROUND
EVT_MOVE = wxEVT_MOVE
EVT_SIZE = wxEVT_SIZE
EVT_SET_FOCUS = wxEVT_SET_FOCUS
EVT_KILL_FOCUS = wxEVT_KILL_FOCUS
EVT_SYS_COLOUR_SCHANGED = wxEVT_SYS_COLOR_CHANGED
EVT_IDLE = wxEVT_IDLE
EVT_UPDATE_UI = wxEVT_UPDATE_UI

EVT_ACTIVATE = wxEVT_ACTIVATE
EVT_CLOSE = wxEVT_CLOSE


wxEVT_MIDDLE_DOWN
